## variables
# AWS_ACCESS_KEY
# AWS_REGION
# AWS_SECRET_KEY
# CI_GITLAB_TOKEN
# INFRACOST_API_KEY

include:
  - project: vkpr/templates
    file: 
      - Full-Workflow-GitLab-Backend.gitlab-ci.yml
      - Full-Worflow-infracost.gitlab-ci.yml
      - Security-Checkov.gitlab-ci.yml

variables:
  TF_VAR_aws_access_key: "$AWS_ACCESS_KEY"
  TF_VAR_aws_secret_key: "$AWS_SECRET_KEY"
  TF_VAR_aws_region: "$AWS_REGION"

stages:
  - iac_init
  - iac_build
  - iac_infra_status
  - iac_deploy
  - iac_destroy

init:
  stage: iac_init
  variables:
    CI_GITLAB_TOKEN: $CI_GITLAB_TOKEN
  extends: .init

validate:
  stage: iac_init
  extends: .validate

build:
  stage: iac_build
  extends: .build

security:
  stage: iac_infra_status
  extends: .checkov
  needs:
    - build
  dependencies:
    - build

infracost:
  stage: iac_infra_status
  variables:
    INFRACOST_API_KEY: $INFRACOST_API_KEY
  extends: .infracost
  needs:
    - build
  dependencies:
    - build

refresh:
  stage: iac_deploy
  extends: .refresh

deploy:
  stage: iac_deploy
  extends: .deploy

destroy:
  stage: iac_destroy
  extends: .destroy
